#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

ln -sf /sbin/ip /usr/bin/ip

sed -i 's/http/https/g' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

rm -rf /tmp/luci-*

sed -i 's/root::0:0:99999:7:::/root:$1$7f4YP/NX$VEZzIMnAEu36noAjugtp2.:18280:0:99999:7:::/g' /etc/shadow

uci set luci.main.mediaurlbase=/luci-static/argon
uci commit luci

uci set network.lan.ipaddr="10.0.0.2"
uci set network.lan.ifname="eth1 eth3"
uci set network.wan.proto=pppoe
uci set network.wan.ifname=eth2
uci set network.wan.username=07399254173
uci set network.wan.password=139715
uci commit network

/etc/init.d/amule disable
chmod -R 777 /www/nas/
cp -R /www/cgi-bin/luci /www/
mv /www/ariang /www/ng

ln -sf /usr/bin/python3 /usr/bin/python
ln -sf /usr/bin/python /usr/bin/py
ln -sf /usr/lib/netdata/conf.d /etc/netdata/conf.d
ln /usr/lib/netdata/conf.d/charts.d.conf /etc/netdata/charts.d.conf
ln /usr/lib/netdata/conf.d/python.d.conf /etc/netdata/python.d.conf
ln -f /etc/netdata/charts.d.conf /usr/lib/netdata/conf.d/charts.d.conf
ln -f /etc/netdata/python.d.conf /usr/lib/netdata/conf.d/python.d.conf

exit 0



